### ISSUE TITLE
How to programmatically handle and correct Poseidon::Errors::OffsetOutOfRange

### ISSUE THREAD

**Issue by rqc** [bsm/poseidon_cluster#7]
Hello,

I have a consumer using _poseidon_cluster (0.1.1) / poseidon (0.0.4)_ that reads data from kafka and writes de data to a database. We had some issues with our database in our staging environment and it caused our consumers to die. When we restarted them, the offset for that particular topic + group apparently got corrupted since we are getting the following exception:

```
/gems/poseidon-0.0.4/lib/poseidon/partition_consumer.rb:98:in `fetch': Poseidon::Errors::OffsetOutOfRange (Poseidon::Errors::OffsetOutOfRange)
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:259:in `block in fetch'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:229:in `checkout'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:258:in `fetch'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:332:in `block in fetch_loop'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:330:in `loop'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:330:in `fetch_loop'
        from /Users/myuser/myconsumerproject/consumer.rb:167:in `block in start'
        from /Users/myuser/myconsumerproject/consumer.rb:131:in `fork'
        from /Users/myuser/myconsumerproject/consumer.rb:131:in `start'
        from run.rb:70:in `<main>'
```

A bit of digging in the kafka docs reveals that this could be resolved using `largest` or `smallest` for `auto.offset.reset`config. http://kafka.apache.org/documentation.html#consumerconfigs

In the Poseidon Cluster's ConsumerGroup https://github.com/bsm/poseidon_cluster/blob/master/lib/poseidon/consumer_group.rb#L40  I can see that we can pass in the `options` hash a key value like this: `:trail =>  :latest_offset`  or `:trail => :earliest_offset` depending on whether you want `largest` or `smallest` to be the offset reset. Thus, I added that to the instantiation of my ConsumerGroup object as such:

```
      consumer = Poseidon::ConsumerGroup.new(
          self.group,
          self.kafka_brokers,
          self.zookeeper_hosts,
          self.topic_name, { :trail => :latest_offset})
```

Now, I get the following error:

```
/gems/poseidon-0.0.4/lib/poseidon/partition_consumer.rb:125:in `handle_options': Unknown options: [:trail] (ArgumentError)
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon-0.0.4/lib/poseidon/partition_consumer.rb:69:in `initialize'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:40:in `initialize'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:377:in `new'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:377:in `claim!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:412:in `block in perform_rebalance!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:411:in `each'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:411:in `perform_rebalance!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:361:in `block in rebalance!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:361:in `synchronize'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:361:in `rebalance!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:147:in `register!'
        from /Users/myuser/.rvm/gems/ruby-2.1.2@consumer-gemset/gems/poseidon_cluster-0.1.1/lib/poseidon/consumer_group.rb:103:in `initialize'
        from /Users/myuser/myconsumerproject/consumer.rb:152:in `new'
        from /Users/myuser/myconsumerproject/consumer.rb:152:in `block in start'
        from /Users/myuser/myconsumerproject/consumer.rb:131:in `fork'
        from /Users/myuser/myconsumerproject/consumer.rb:131:in `start'
        from run.rb:70:in `<main>'
```

So, my question is, what seems to be the issue here? Am I using the poseidon_cluster API correctly by passing the key-value pair? I am not sure why it at least not defaulting to `earliest_offset` since the check in https://github.com/bsm/poseidon_cluster/blob/master/lib/poseidon/consumer_group.rb#L40 seems to default to that if the offset is zero for a given partition. I also double checked and all partitions are returning offset of zero. I would really appreciate some help here if possible. Thanks!

Ricardo

**Comment by richardwan** [comment]
when are these fixes getting released to rubygems?
